# This workflow will reset the Maven dependencies for a Java project with Maven

name: Maven Reset Dependencies

on:
  workflow_dispatch:

jobs:
  reset:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Reset Maven Dependencies
      run: mvn dependency:purge-local-repository
