# This workflow will reset the Maven dependencies for a Java project with Maven

name: Maven Reset Dependencies

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        check-latest: true
    - name: Reset Maven Dependencies
      run: mvn dependency:purge-local-repository
    - name: Reload Maven Dependencies
      run: mvn clean install -U
    - name: Delete JONLD repository files
      run: rm -r ~/.m2/repository/com/github/jsonld-java/*
    - name: Build with Maven
      run: mvn -B package --file pom.xml
